import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { getFirestore, collection, doc, onSnapshot, setDoc } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';

const BUILD='2.0.0-preview.2';
const AGENT='http://127.0.0.1:8765/api/v1';
const LINES=['TAN10101','TAN10102','TAN10103'];
const NAMES={TAN10101:'Linha 1',TAN10102:'Linha 2',TAN10103:'Linha 3'};
const FIREBASE={apiKey:'AIzaSyBi8ll-uiEh9L9sPBXQZhqIbFxgLfnTjeM',authDomain:'central-de-controle-88962.firebaseapp.com',projectId:'central-de-controle-88962',storageBucket:'central-de-controle-88962.firebasestorage.app',messagingSenderId:'557459646371',appId:'1:557459646371:web:e5bfb77bfbcad6d50bdc16'};
const fb=getApps().find(x=>x.name==='central-v2-native')||initializeApp(FIREBASE,'central-v2-native');
const auth=getAuth(fb),db=getFirestore(fb);
const S={user:null,agent:false,local:new Map(),remote:new Map(),line:'TAN10101',tab:'overview',busy:false,sig:'',observer:null};
const e=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number(v||0).toLocaleString('pt-BR');
const pc=v=>(v===null||v===undefined||v==='')?'—':`${Number(v).toFixed(2)}%`;
const src=l=>S.local.get(l)||S.remote.get(l)||null;
const name=l=>NAMES[l]||l;
const key=v=>String(v||'').toUpperCase().replace(/^CHP/,'CPH').replace(/^CPH/,'').replace(/[^A-Z0-9]/g,'');
async function getJSON(url,timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}finally{clearTimeout(t)}}
const agent=(p,t)=>getJSON(`${AGENT}${p}`,t);
function clean(r){return {line:r.line||'',pcba_sn:r.pcba_sn||'',defect_time:r.defect_time||'',defect_code:r.defect_code||'',defect_desc:String(r.defect_desc||'').slice(0,220),product_model:r.product_model||'',repair_status_current:r.repair_status_current||'',repair_state_current:r.repair_state_current||'',defect_type_current:r.defect_type_current||''}}
function cleanInsights(x){if(!x?.ready)return {ready:false};const dc={};for(const [k,v] of Object.entries(x.drilldowns||{}))dc[k]=Array.isArray(v)?v.length:0;return {ready:true,rate_kpis:x.rate_kpis||[],pcba_kpis:x.pcba_kpis||[],material_kpis:x.material_kpis||[],correlation_kpis:x.correlation_kpis||[],component_types:(x.component_types||[]).slice(0,50),drilldown_counts:dc}}
function text(p){const s=p.summary||{},i=p.insights||{},top=(s.top3||[]).map(x=>`${x.defect_code||x.code||''} ${x.defect_desc||x.desc||''} (${x.qty||x.count||0})`).join('; '),kv=a=>(a||[]).map(x=>`${x[0]}: ${x[1]}`).join('; ');return `A-MES ${name(p.line)} ${p.line}. Snapshot ${s.snapshot_id||'—'}; FPY ${s.fpy??'—'}; Check FPY ${s.check_fpy??'—'}; Quantity ${s.quantity??'—'}; ocorrências ${s.defect_rows??'—'}; Top3 ${top||'sem dados'}. PCBA ${kv(i.pcba_kpis)}. Materiais ${kv(i.material_kpis)}. Correlações ${kv(i.correlation_kpis)}.`}
async function readLocal(){await agent('/health',3500);S.agent=true;const sh=await agent('/share/export',6000),out=[];for(const sm of sh.lines||[]){if(!LINES.includes(sm.line))continue;let defects=[],insights={ready:false};try{const d=await agent(`/base?dataset=defects&line=${sm.line}&limit=160`,7000);defects=(d.rows||[]).slice(0,160).map(clean)}catch{}try{insights=cleanInsights(await agent(`/insights?line=${sm.line}`,10000))}catch{}const p={schema:'central-v2-ames-line-v1',line:sm.line,summary:sm,defects,insights,generated_at:sh.generated_at||new Date().toISOString()};S.local.set(sm.line,p);out.push(p)}return out}
function sig(ps){return JSON.stringify(ps.map(p=>[p.line,p.summary?.snapshot_id,p.summary?.collected_at,p.defects.length,p.summary?.pcba_history_count,p.summary?.material_reuse_count]))}
async function sync(force=false){if(S.busy||!S.user)return;S.busy=true;try{const ps=await readLocal(),sg=sig(ps);if(!force&&sg===S.sig)return;for(const p of ps)await setDoc(doc(db,'aiKnowledge',`ames-v2-line-${p.line}`),{kind:'ames_shared_snapshot',type:'ames_snapshot',status:'validado_sistema',source:'A-MES',line:p.line,schema:p.schema,generatedAt:p.generated_at,syncedAt:new Date().toISOString(),syncedBy:S.user.email||S.user.uid,text:text(p),payload:p},{merge:true});S.sig=sg}catch(err){console.info('[Central V2] agente local/sync:',err.message);S.agent=false}finally{S.busy=false;renderAll()}}
onAuthStateChanged(auth,u=>{S.user=u||null;if(u)sync(false)});
onSnapshot(collection(db,'aiKnowledge'),snap=>{for(const d of snap.docs){const x=d.data();if(x?.kind==='ames_shared_snapshot'&&LINES.includes(x.line)&&x.payload)S.remote.set(x.line,x.payload)}renderAll()},err=>console.warn('[Central V2] Firestore',err));

function css(){if(document.querySelector('#centralV2NativeStyle'))return;const s=document.createElement('style');s.id='centralV2NativeStyle';s.textContent=`#amesV2{position:fixed;inset:0;z-index:999;background:var(--bg,#f4f4f2);overflow:auto;padding:28px clamp(18px,4vw,52px) 60px}.v2off{display:none!important}.v2wrap{max-width:1500px;margin:auto}.v2h{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:16px}.v2h h1{margin:0;font-size:24px}.v2h p{margin:5px 0;color:var(--muted);font-size:12px}.v2pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:6px 9px;margin-left:5px;background:var(--surface);font-size:10px;font-weight:700}.v2pill.ok{color:#197244;border-color:#b7e4c7}.v2tabs,.v2actions{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:14px}.v2tabs button,.v2actions button,.v2actions a{border:1px solid var(--line);border-radius:8px;padding:8px 11px;background:var(--surface);color:var(--text);font-weight:650;text-decoration:none}.v2tabs button.on,.v2actions .primary{background:#111;color:#fff;border-color:#111}.v2lines{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.v2line{border:1px solid var(--line);border-radius:10px;padding:11px;background:var(--surface);text-align:left}.v2line.on{border-color:#111;box-shadow:0 0 0 1px #111}.v2line b,.v2line small{display:block}.v2line small{color:var(--muted);margin-top:3px}.v2metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.v2m,.v2card,.v2embed{border:1px solid var(--line);border-radius:10px;background:var(--surface);padding:13px}.v2m small,.v2k small{display:block;color:var(--muted);font-size:10px}.v2m b{font-size:22px;display:block;margin-top:6px}.v2card{margin-top:10px}.v2card h3,.v2embed h3{margin:0 0 9px;font-size:14px}.v2kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.v2k{border:1px solid var(--line);border-radius:8px;padding:9px;background:var(--soft,#fafafa)}.v2k b{display:block;font-size:17px;margin-top:5px}.v2note{border:1px solid var(--line);border-radius:8px;padding:10px;background:var(--surface);color:var(--muted);font-size:11px;line-height:1.45}.v2table{width:100%;min-width:760px;border-collapse:collapse}.v2table th,.v2table td{padding:8px;border-bottom:1px solid var(--line);font-size:10px;text-align:left}.v2scroll{overflow:auto}.v2embed{margin:12px 0}.v2embedgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.v2embedgrid>div{border:1px solid var(--line);border-radius:8px;padding:9px}.v2embedgrid small{display:block;color:var(--muted);font-size:9px}.v2embedgrid b{display:block;font-size:16px;margin:4px 0}#amesV2Nav::after{content:'';width:7px;height:7px;border-radius:50%;background:var(--amesDot,#999);margin-left:auto}@media(max-width:900px){.v2metrics{grid-template-columns:repeat(3,1fr)}.v2lines,.v2kpis,.v2embedgrid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function ensureNav(){let b=document.querySelector('#amesV2Nav');if(b)return;b=document.createElement('button');b.id='amesV2Nav';b.innerHTML='<span>⌁</span><span>A-MES integrado</span>';b.onclick=()=>{overlay().classList.remove('v2off');renderOverlay()};const dash=[...document.querySelectorAll('.main-nav button')].find(x=>/dashboard/i.test(x.textContent));(dash?.parentNode||document.querySelector('.main-nav'))?.insertBefore(b,dash?.nextSibling||null)}
function overlay(){let o=document.querySelector('#amesV2');if(o)return o;o=document.createElement('section');o.id='amesV2';o.className='v2off';document.body.appendChild(o);return o}
function lineTabs(){return `<div class="v2lines">${LINES.map(l=>{const p=src(l),s=p?.summary||{};return `<button class="v2line ${S.line===l?'on':''}" data-v2line="${l}"><b>${name(l)}</b><small>${l}${p?` · FPY ${pc(s.fpy)} · ${n(s.defect_rows)} falhas`:' · sem dados'}</small></button>`}).join('')}</div>`}
function metrics(p){const s=p.summary||{};return `<div class="v2metrics"><div class="v2m"><small>FPY</small><b>${pc(s.fpy)}</b></div><div class="v2m"><small>Check FPY</small><b>${pc(s.check_fpy)}</b></div><div class="v2m"><small>Quantity</small><b>${n(s.quantity)}</b></div><div class="v2m"><small>Ocorrências</small><b>${n(s.defect_rows)}</b></div><div class="v2m"><small>Históricos 2114</small><b>${n(s.pcba_history_count)}</b></div><div class="v2m"><small>Materiais 3074</small><b>${n(s.material_reuse_count)}</b></div></div>`}
function kpis(p){const i=p.insights||{};return [['PCBA reutilizada',i.pcba_kpis],['Material reutilizado',i.material_kpis],['Recorrência',i.correlation_kpis]].map(([t,a])=>`<div class="v2card"><h3>${t}</h3><div class="v2kpis">${(a||[]).map(x=>`<div class="v2k"><small>${e(x[0])}</small><b>${e(x[1])}</b></div>`).join('')||'<div class="v2note">Sem dados ainda.</div>'}</div></div>`).join('')}
function defectTable(p){return `<div class="v2card"><h3>Falhas recentes</h3><div class="v2scroll"><table class="v2table"><thead><tr><th>PCBA</th><th>Modelo</th><th>Código</th><th>Descrição</th><th>Repair</th><th>Defect time</th></tr></thead><tbody>${(p.defects||[]).slice(0,100).map(r=>`<tr><td>${e(r.pcba_sn)}</td><td>${e(r.product_model)}</td><td>${e(r.defect_code)}</td><td>${e(r.defect_desc)}</td><td>${e(r.repair_status_current||r.repair_state_current)}</td><td>${e(r.defect_time)}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderOverlay(){const o=overlay(),p=src(S.line);o.innerHTML=`<div class="v2wrap"><div class="v2h"><div><h1>Central de Trabalho V2</h1><p>A-MES conectado ao mesmo produto: operação, produto, turno, recorrência e CORA compartilham a mesma base de evidências.</p></div><div><span class="v2pill ${S.agent?'ok':''}">${S.agent?'● agente local':'○ dados sincronizados'}</span><span class="v2pill">${BUILD}</span><button id="v2close">Fechar</button></div></div><div class="v2tabs"><button data-v2tab="overview" class="${S.tab==='overview'?'on':''}">Operação</button><button data-v2tab="reuse" class="${S.tab==='reuse'?'on':''}">Reuso & recorrência</button><button data-v2tab="sync" class="${S.tab==='sync'?'on':''}">Sincronização</button><button data-v2tab="roadmap" class="${S.tab==='roadmap'?'on':''}">Inteligência V2</button></div>${lineTabs()}<div id="v2body"></div></div>`;o.querySelector('#v2close').onclick=()=>o.classList.add('v2off');o.querySelectorAll('[data-v2line]').forEach(b=>b.onclick=()=>{S.line=b.dataset.v2line;renderOverlay()});o.querySelectorAll('[data-v2tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.v2tab;renderOverlay()});const body=o.querySelector('#v2body');if(S.tab==='overview')body.innerHTML=p?metrics(p)+defectTable(p):'<div class="v2note">Sem snapshot desta linha.</div>';if(S.tab==='reuse')body.innerHTML=p?metrics(p)+kpis(p)+defectTable(p):'<div class="v2note">Sem rastreabilidade desta linha.</div>';if(S.tab==='sync')body.innerHTML=`<div class="v2card"><h3>Fábrica ↔ Central</h3><div class="v2note">Com o agente 8765 disponível, esta Central usa os dados locais e sincroniza somente snapshots sanitizados para o Firebase. Fora da fábrica, lê o último sincronizado. Credenciais/sessão MES não saem do notebook.</div><div class="v2actions" style="margin-top:10px"><button id="v2detect" class="primary">Detectar agente</button><button id="v2sync">Sincronizar agora</button></div></div>`;if(S.tab==='roadmap')body.innerHTML=`<div class="v2card"><h3>Como a V2 usa o A-MES</h3><div class="v2note"><b>Dashboard:</b> FPY, recorrência e reuso por linha. <b>Produtos/CPH:</b> ocorrências reais do modelo. <b>Central do Dia:</b> saúde da linha e padrões do turno. <b>CORA:</b> snapshots A-MES entram em aiKnowledge como evidência validada pelo sistema. <b>Próxima camada:</b> 3022 adicionará processo/posto/hora antes da falha.</div></div>`;body.querySelector('#v2detect')?.addEventListener('click',()=>detect(true));body.querySelector('#v2sync')?.addEventListener('click',()=>sync(true))}
function embedDashboard(){const active=[...document.querySelectorAll('.main-nav button.active')].map(x=>x.textContent).join(' ');if(!/dashboard/i.test(active))return;const c=document.querySelector('.content');if(!c)return;let h=document.querySelector('#v2Dash');if(!h){h=document.createElement('section');h.id='v2Dash';h.className='v2embed';c.prepend(h)}h.innerHTML=`<h3>A-MES · operação atual</h3><div class="v2embedgrid">${LINES.map(l=>{const p=src(l),s=p?.summary||{};return `<div><small>${name(l)} · ${l}</small><b>${p?pc(s.fpy):'sem dados'}</b><small>${p?`Check ${pc(s.check_fpy)} · ${n(s.defect_rows)} falhas`:'aguardando sincronização'}</small></div>`}).join('')}</div>`}
function embedProduct(){const title=(document.querySelector('.page-title')?.textContent||'').trim(),k=key(title),c=document.querySelector('.content');if(!k||!/^\d{4}/.test(k)||!c)return;const found=[];for(const l of LINES){const p=src(l);if(!p)continue;const rows=(p.defects||[]).filter(r=>{const m=key(r.product_model);return m===k||m.startsWith(k)||k.startsWith(m)});if(rows.length)found.push({l,rows})}let h=document.querySelector('#v2Prod');if(!h){h=document.createElement('section');h.id='v2Prod';h.className='v2embed';c.prepend(h)}h.innerHTML=`<h3>A-MES · evidência deste CPH</h3>${found.length?`<div class="v2embedgrid">${found.map(x=>`<div><small>${name(x.l)} · ${x.l}</small><b>${x.rows.length} ocorrência(s)</b><small>Dados da coleta MES associados a este modelo</small></div>`).join('')}</div>`:'<div class="v2note">Sem ocorrências A-MES sincronizadas para este CPH.</div>'}`}
function embedDaily(){const p=document.querySelector('#dailyRecurrencePanel');if(!p)return;let h=document.querySelector('#v2Daily');if(!h){h=document.createElement('div');h.id='v2Daily';h.className='v2embed';p.appendChild(h)}h.innerHTML=`<h3>A-MES no turno</h3><div class="v2embedgrid">${LINES.map(l=>{const q=src(l),s=q?.summary||{};return `<div><small>${name(l)}</small><b>${q?pc(s.fpy):'—'}</b><small>${q?`${n(s.defect_rows)} falhas · ${n(s.pcba_history_count)} histórias 2114`:'sem snapshot'}</small></div>`}).join('')}</div>`}
function embedCora(){const p=document.querySelector('#aiMemoryPanel');if(!p)return;let h=document.querySelector('#v2Cora');if(!h){h=document.createElement('div');h.id='v2Cora';h.className='ai-memory-card';p.prepend(h)}h.innerHTML=`<strong>A-MES integrado à CORA</strong><p>${LINES.filter(l=>src(l)).length} linha(s) com contexto estruturado. Os snapshots sincronizados ficam em aiKnowledge com status validado pelo sistema e entram na busca contextual existente.</p>`}
function renderAll(){css();ensureNav();embedDashboard();embedProduct();embedDaily();embedCora();const b=document.querySelector('#amesV2Nav');if(b)b.style.setProperty('--amesDot',S.agent?'#20a464':'#999');if(!overlay().classList.contains('v2off'))renderOverlay()}
async function detect(force=false){try{await readLocal();if(S.user)await sync(force)}catch{S.agent=false;S.local.clear()}renderAll()}
function boot(){css();ensureNav();overlay();S.observer=new MutationObserver(()=>renderAll());S.observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});renderAll();detect(false);setInterval(()=>detect(false),60000);window.__CENTRAL_V2__={build:BUILD,state:S,detect:()=>detect(true),sync:()=>sync(true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
